# Generated by Django 5.0.1 on 2024-01-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_order_discount_alter_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
