# Generated by Django 5.0.1 on 2024-01-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_fully_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rest_money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
