# Generated by Django 5.0.1 on 2024-01-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_shop',
            field=models.BooleanField(default=False),
        ),
    ]
