# Generated by Django 5.0.1 on 2024-01-29 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_customer_is_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('total_order_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_fully_paid', models.BooleanField(default=True)),
                ('rest_money', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coming_orders', to='main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Store_OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_real_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_gomla_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('single_real_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('single_gomla_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('single_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main.store_order')),
            ],
        ),
    ]
