# Generated by Django 5.0.1 on 2024-01-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_store_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_orderitem',
            name='change_gomla_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='store_orderitem',
            name='change_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='store_orderitem',
            name='change_real_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
