# Generated by Django 5.0.1 on 2024-01-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_store_orderitem_is_done_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_orderitem',
            name='is_done',
        ),
        migrations.AddField(
            model_name='store_order',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
