# Generated by Django 5.0.1 on 2024-02-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_order',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
