# Generated by Django 5.0.1 on 2024-02-07 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_item_gomla_price_alter_item_market_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store_order',
            name='supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='main.customer'),
        ),
    ]
