# Generated by Django 5.0.1 on 2024-01-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist_item',
            old_name='users',
            new_name='user',
        ),
    ]
