# Generated by Django 5.0.1 on 2024-01-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_users_watchlist_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
